### PR TITLE
Linkcolor

### PR DESCRIPTION
**Pull request by dominikpegler**

### CODE REVIEW

**Comment by agl4** [comment]
Updated the target branch to `norma`. Use this please.

**Comment by agl4** [comment]
I like it. Can I merge it, are you finished with this? We have to tune the logo as well to this color.

**Comment by dominikpegler** [comment]
yeah, I like the neutral gray in the logo. It harmonizes with all pictures and content

**Comment by dominikpegler** [comment]
I especially saw this beneficial when watching your bw series. A color in a logo is just always a statement

**Comment by dominikpegler** [comment]
why is this open again? @agoloncser

**Pull request merged**
