### PR TITLE
rm h1

### PR DESCRIPTION
**Pull request by dominikpegler**
here we go

### CODE REVIEW

**Comment by agl4** [comment]
I added your changes to this branch https://github.com/normanormanorma/minimo/tree/AGL21-112-apply-changes, please merge it on this one.

**Comment by agl4** [comment]
I merged it locally and the state after the merge:
- home page OK
- about page OK
- projects page is still having the heading.

**Comment by agl4** [comment]
Can't we do these changes in the main repo? I mean these partials can be "copied" to the other repo so they will override what is in the theme? Isn't it working that way?

**Comment by dominikpegler** [comment]
yes

**Pull request closed without merging**
